name: 'Atmos Affected Stacks Trigger Spacelift'
description: 'A GitHub action to trigger the corresponding Spacelift Stack from atmos describe affected'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  spacelift-endpoint:
    required: true
    description: "The Spacelift endpoint. For example, https://unicorn.app.spacelift.io"
  spacelift-api-key-id:
    required: true
    description: The SPACELIFT_API_KEY_ID
  spacelift-api-key-secret:
    required: true
    description: The SPACELIFT_API_KEY_SECRET
  deploy:
    required: true
    default: "false"
    description: A flag to indicate if a deployment should be trigged. If false, a preview will be triggered.
  default-branch:
    description: The default branch to use for the base ref.
    required: false
    default: ${{ github.event.repository.default_branch }}
  head-ref:
    description: The head ref to checkout. If not provided, the head default branch is used.
    required: false
  install-atmos:
    description: Whether to install atmos
    required: false
    default: "true"
  atmos-version:
    description: The version of atmos to install if install-atmos is true
    required: false
    default: "latest"
  install-spacectl:
    description: Whether to install spacectl
    required: false
    default: "true"
  spacectl-version:
    description: The version of spacectl to install if install-spacectl is true
    required: false
    default: "latest"
  install-terraform:
    description: Whether to install terraform
    required: false
    default: "true"
  terraform-version:
    description: The version of terraform to install if install-terraform is true
    required: false
    default: "latest"
  install-jq:
    description: Whether to install jq
    required: false
    default: "false"
  jq-version:
    description: The version of jq to install if install-jq is true
    required: false
    default: "1.6"
  jq-force:
    description: Whether to force the installation of jq
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Atmos Affected Stacks
      id: affected-stacks
      uses: cloudposse/github-action-atmos-affected-stacks@0.0.1
      with:
        default-branch: ${{inputs.default-branch}}
        head-ref: ${{inputs.head-ref}}
        install-atmos: ${{inputs.install-atmos}}
        atmos-version: ${{inputs.atmos-version}}
        install-terraform: ${{inputs.install-terraform}}
        terraform-version: ${{inputs.terraform-version}}
        install-jq: ${{inputs.install-jq}}
        jq-version: ${{inputs.jq-version}}
        jq-force: ${{inputs.jq-force}}

    - name: Setup Spacectl
      if: ${{ inputs.install-spacectl == 'true' }}
      uses: spacelift-io/setup-spacectl@v0.3.0
      with:
        version: ${{inputs.spacectl-version}}

    - name: Trigger Spacelift Stacks
      shell: bash
      env:
        SPACELIFT_API_KEY_ENDPOINT: ${{inputs.spacelift-endpoint}}
        SPACELIFT_API_KEY_ID: ${{ inputs.spacelift-api-key-id }}
        SPACELIFT_API_KEY_SECRET: ${{ inputs.spacelift-api-key-secret }}
      run: |
        spacectl_deploy="false"
        if [ "${{inputs.deploy}}" = "true" ]; then
          spacectl_deploy="true"
        fi
        ./scripts/spacelift-trigger-affected-stacks.sh ${{ steps.affected-stacks.outputs.affected }} $spacectl_deploy

