name: release-published

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-major-release-tagger@v1
        with:
          log-level: 'debug'
          dry-run: true