name: Test Changes
on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cloudposse-github-actions/install-gh-releases@v1
        with:
          cache: true
          config: |-
            mikefarah/yq: v4.44.3

      # Make a change
      - name: Make a change
        run: |
          yq -i '.components.terraform.test.vars.seed = 2' ./tests/stacks/orgs/test/test.yaml

      - uses: ./
        id: current
        with:
          atmos-config-path: ./tests
          install-atmos: true

    outputs:
      affected: "${{ steps.current.outputs.affected }}"
      has-affected-stacks: "${{ steps.current.outputs.has-affected-stacks }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: '[{"component":"test","component_type":"terraform","component_path":"tests/components/terraform/test","stack":"test-t-test","stack_slug":"test-t-test-test","affected":"stack.metadata","dependents":null,"included_in_dependents":false,"settings":null}]' 
          actual: "${{ needs.test.outputs.affected }}"

      - uses: nick-fields/assert-action@v2
        with:
          expected: 'true'
          actual: "${{ needs.test.outputs.has-affected-stacks }}"