name: Test No Changes
on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # There should be no changes
      - uses: ./
        id: current
        with:
          atmos-config-path: ./tests
          install-atmos: true
          # Set both the head and default branch to the PR branch.
          # We intentionally want to validate there are no changes
          head-ref: ${{ github.event.pull_request.head.ref }} 
          default-branch: ${{ github.event.pull_request.head.ref }}

    outputs:
      affected: "${{ steps.current.outputs.affected }}"
      has-affected-stacks: "${{ steps.current.outputs.has-affected-stacks }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: '[]'
          actual: "${{ needs.test.outputs.affected }}"

      - uses: nick-fields/assert-action@v2
        with:
          expected: 'false'
          actual: "${{ needs.test.outputs.has-affected-stacks }}"